"""token version

Revision ID: 689231f99eca
Revises: b0d35cc5876e
Create Date: 2026-06-30 01:04:58.902219+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '689231f99eca'
down_revision: str | None = 'b0d35cc5876e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('token_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'token_version')
    # ### end Alembic commands ###
