"""initial schema

Revision ID: 2d537fa5afd6
Revises: 
Create Date: 2026-06-28 12:38:25.286353+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d537fa5afd6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_deleted_at'), 'admin_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('brands',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('brand_type', sa.String(), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_deleted_at'), 'brands', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_deleted_at'), 'api_keys', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_action_type'), 'approval_requests', ['action_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_brand_id'), 'approval_requests', ['brand_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_deleted_at'), 'approval_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_entity_id'), 'approval_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_approval_requests_requested_by_user_id'), 'approval_requests', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('audiences',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('segment_rules', sa.JSON(), nullable=False),
    sa.Column('size_estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiences_brand_id'), 'audiences', ['brand_id'], unique=False)
    op.create_index(op.f('ix_audiences_deleted_at'), 'audiences', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_audiences_id'), 'audiences', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_deleted_at'), 'audit_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('brand_voices',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('writing_sample', sa.Text(), nullable=True),
    sa.Column('do_list', sa.JSON(), nullable=False),
    sa.Column('dont_list', sa.JSON(), nullable=False),
    sa.Column('value_props', sa.JSON(), nullable=False),
    sa.Column('vocabulary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_voices_brand_id'), 'brand_voices', ['brand_id'], unique=True)
    op.create_index(op.f('ix_brand_voices_deleted_at'), 'brand_voices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_brand_voices_id'), 'brand_voices', ['id'], unique=False)
    op.create_table('buyer_personas',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('pain_points', sa.JSON(), nullable=False),
    sa.Column('objections', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('demographics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_personas_brand_id'), 'buyer_personas', ['brand_id'], unique=False)
    op.create_index(op.f('ix_buyer_personas_deleted_at'), 'buyer_personas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_buyer_personas_id'), 'buyer_personas', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_brand_id'), 'companies', ['brand_id'], unique=False)
    op.create_index(op.f('ix_companies_deleted_at'), 'companies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('content_calendars',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_calendars_brand_id'), 'content_calendars', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_calendars_deleted_at'), 'content_calendars', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_content_calendars_id'), 'content_calendars', ['id'], unique=False)
    op.create_table('conversion_goals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('value_cents', sa.Integer(), nullable=True),
    sa.Column('funnel_stage', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_goals_brand_id'), 'conversion_goals', ['brand_id'], unique=False)
    op.create_index(op.f('ix_conversion_goals_deleted_at'), 'conversion_goals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversion_goals_id'), 'conversion_goals', ['id'], unique=False)
    op.create_table('email_templates',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('preheader', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_template_brand_slug')
    )
    op.create_index(op.f('ix_email_templates_brand_id'), 'email_templates', ['brand_id'], unique=False)
    op.create_index(op.f('ix_email_templates_deleted_at'), 'email_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_email_templates_slug'), 'email_templates', ['slug'], unique=False)
    op.create_table('hashtags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_brand_id'), 'hashtags', ['brand_id'], unique=False)
    op.create_index(op.f('ix_hashtags_deleted_at'), 'hashtags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_hashtags_id'), 'hashtags', ['id'], unique=False)
    op.create_index(op.f('ix_hashtags_tag'), 'hashtags', ['tag'], unique=False)
    op.create_table('hooks',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hooks_brand_id'), 'hooks', ['brand_id'], unique=False)
    op.create_index(op.f('ix_hooks_deleted_at'), 'hooks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_hooks_id'), 'hooks', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_brand_id'), 'notes', ['brand_id'], unique=False)
    op.create_index(op.f('ix_notes_deleted_at'), 'notes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notes_entity_id'), 'notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notes_entity_type'), 'notes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('offers',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('offer_type', sa.String(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('stripe_price_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('stripe_payment_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('asset_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('asset_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('delivery_template_slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_offer_brand_slug')
    )
    op.create_index(op.f('ix_offers_brand_id'), 'offers', ['brand_id'], unique=False)
    op.create_index(op.f('ix_offers_deleted_at'), 'offers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_name'), 'offers', ['name'], unique=False)
    op.create_index(op.f('ix_offers_slug'), 'offers', ['slug'], unique=False)
    op.create_table('pillars',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pillars_brand_id'), 'pillars', ['brand_id'], unique=False)
    op.create_index(op.f('ix_pillars_deleted_at'), 'pillars', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pillars_id'), 'pillars', ['id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_stage_brand_slug')
    )
    op.create_index(op.f('ix_pipeline_stages_brand_id'), 'pipeline_stages', ['brand_id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_deleted_at'), 'pipeline_stages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_id'), 'pipeline_stages', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_slug'), 'pipeline_stages', ['slug'], unique=False)
    op.create_table('segments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_brand_id'), 'segments', ['brand_id'], unique=False)
    op.create_index(op.f('ix_segments_deleted_at'), 'segments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_segments_id'), 'segments', ['id'], unique=False)
    op.create_table('sender_identities',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('from_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('from_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('reply_to', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('resend_domain_id', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sender_identities_brand_id'), 'sender_identities', ['brand_id'], unique=False)
    op.create_index(op.f('ix_sender_identities_deleted_at'), 'sender_identities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sender_identities_id'), 'sender_identities', ['id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('connection_meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_brand_id'), 'social_accounts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_deleted_at'), 'social_accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.create_table('suppressions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'email', name='uq_suppression_brand_email')
    )
    op.create_index(op.f('ix_suppressions_brand_id'), 'suppressions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_suppressions_deleted_at'), 'suppressions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_suppressions_email'), 'suppressions', ['email'], unique=False)
    op.create_index(op.f('ix_suppressions_id'), 'suppressions', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name', name='uq_tag_brand_name')
    )
    op.create_index(op.f('ix_tags_brand_id'), 'tags', ['brand_id'], unique=False)
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('tasks',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_user_id'), 'tasks', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_brand_id'), 'tasks', ['brand_id'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_reminder_at'), 'tasks', ['reminder_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('utm_links',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_medium', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_term', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_content', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('short_code', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utm_links_brand_id'), 'utm_links', ['brand_id'], unique=False)
    op.create_index(op.f('ix_utm_links_deleted_at'), 'utm_links', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_utm_links_id'), 'utm_links', ['id'], unique=False)
    op.create_index(op.f('ix_utm_links_short_code'), 'utm_links', ['short_code'], unique=True)
    op.create_table('campaigns',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_campaign_brand_slug')
    )
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_campaigns_deleted_at'), 'campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_slug'), 'campaigns', ['slug'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('lifecycle_stage', sa.String(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_brand_id'), 'contacts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_deleted_at'), 'contacts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_lead_score'), 'contacts', ['lead_score'], unique=False)
    op.create_index(op.f('ix_contacts_lifecycle_stage'), 'contacts', ['lifecycle_stage'], unique=False)
    op.create_index(op.f('ix_contacts_owner_user_id'), 'contacts', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_source'), 'contacts', ['source'], unique=False)
    op.create_table('ctas',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ctas_brand_id'), 'ctas', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ctas_deleted_at'), 'ctas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ctas_id'), 'ctas', ['id'], unique=False)
    op.create_table('revenue_goals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('target_cents', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_goals_brand_id'), 'revenue_goals', ['brand_id'], unique=False)
    op.create_index(op.f('ix_revenue_goals_deleted_at'), 'revenue_goals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_revenue_goals_id'), 'revenue_goals', ['id'], unique=False)
    op.create_table('sequences',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('sequence_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('stop_on_goal', sa.Boolean(), nullable=False),
    sa.Column('goal_event', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('stop_on_reply', sa.Boolean(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug', name='uq_sequence_brand_slug')
    )
    op.create_index(op.f('ix_sequences_brand_id'), 'sequences', ['brand_id'], unique=False)
    op.create_index(op.f('ix_sequences_deleted_at'), 'sequences', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sequences_id'), 'sequences', ['id'], unique=False)
    op.create_index(op.f('ix_sequences_slug'), 'sequences', ['slug'], unique=False)
    op.create_index(op.f('ix_sequences_status'), 'sequences', ['status'], unique=False)
    op.create_table('deals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_stage_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_brand_id'), 'deals', ['brand_id'], unique=False)
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_contact_id'), 'deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_deals_deleted_at'), 'deals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_owner_user_id'), 'deals', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_deals_pipeline_stage_id'), 'deals', ['pipeline_stage_id'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_table('forms',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('lead_magnet_offer_id', sa.Uuid(), nullable=True),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('consent_required', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('double_optin', sa.Boolean(), nullable=False),
    sa.Column('success_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('redirect_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tags_to_apply', sa.JSON(), nullable=False),
    sa.Column('notify_emails', sa.JSON(), nullable=False),
    sa.Column('enroll_sequence_id', sa.Uuid(), nullable=True),
    sa.Column('embed_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['enroll_sequence_id'], ['sequences.id'], ),
    sa.ForeignKeyConstraint(['lead_magnet_offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_brand_id'), 'forms', ['brand_id'], unique=False)
    op.create_index(op.f('ix_forms_deleted_at'), 'forms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_forms_id'), 'forms', ['id'], unique=False)
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=True)
    op.create_table('leads',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('referral_source', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('consent_status', sa.String(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('double_optin_token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('double_optin_sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('interested_offer_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['interested_offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'email', name='uq_lead_brand_email')
    )
    op.create_index(op.f('ix_leads_brand_id'), 'leads', ['brand_id'], unique=False)
    op.create_index(op.f('ix_leads_consent_status'), 'leads', ['consent_status'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_deleted_at'), 'leads', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_leads_double_optin_token'), 'leads', ['double_optin_token'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_table('sequence_steps',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('send_window', sa.JSON(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_steps_deleted_at'), 'sequence_steps', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sequence_steps_id'), 'sequence_steps', ['id'], unique=False)
    op.create_index(op.f('ix_sequence_steps_sequence_id'), 'sequence_steps', ['sequence_id'], unique=False)
    op.create_table('social_campaigns',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('persona_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['buyer_personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_campaigns_brand_id'), 'social_campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_social_campaigns_deleted_at'), 'social_campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_social_campaigns_id'), 'social_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_social_campaigns_status'), 'social_campaigns', ['status'], unique=False)
    op.create_table('ab_tests',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_step_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('winner_variant', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['sequence_step_id'], ['sequence_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_tests_brand_id'), 'ab_tests', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_deleted_at'), 'ab_tests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ab_tests_id'), 'ab_tests', ['id'], unique=False)
    op.create_table('consent_records',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_brand_id'), 'consent_records', ['brand_id'], unique=False)
    op.create_index(op.f('ix_consent_records_deleted_at'), 'consent_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_consent_records_id'), 'consent_records', ['id'], unique=False)
    op.create_index(op.f('ix_consent_records_lead_id'), 'consent_records', ['lead_id'], unique=False)
    op.create_table('content_items',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('calendar_id', sa.Uuid(), nullable=True),
    sa.Column('social_campaign_id', sa.Uuid(), nullable=True),
    sa.Column('pillar_id', sa.Uuid(), nullable=True),
    sa.Column('hook_id', sa.Uuid(), nullable=True),
    sa.Column('cta_id', sa.Uuid(), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('source_content_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('video_script', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['calendar_id'], ['content_calendars.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['cta_id'], ['ctas.id'], ),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], ),
    sa.ForeignKeyConstraint(['social_campaign_id'], ['social_campaigns.id'], ),
    sa.ForeignKeyConstraint(['source_content_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_brand_id'), 'content_items', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_items_campaign_id'), 'content_items', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_items_channel'), 'content_items', ['channel'], unique=False)
    op.create_index(op.f('ix_content_items_deleted_at'), 'content_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_content_items_id'), 'content_items', ['id'], unique=False)
    op.create_index(op.f('ix_content_items_scheduled_at'), 'content_items', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_content_items_social_campaign_id'), 'content_items', ['social_campaign_id'], unique=False)
    op.create_index(op.f('ix_content_items_state'), 'content_items', ['state'], unique=False)
    op.create_table('enrollments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('stop_reason', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'lead_id', name='uq_enrollment_seq_lead')
    )
    op.create_index(op.f('ix_enrollments_brand_id'), 'enrollments', ['brand_id'], unique=False)
    op.create_index(op.f('ix_enrollments_contact_id'), 'enrollments', ['contact_id'], unique=False)
    op.create_index(op.f('ix_enrollments_deleted_at'), 'enrollments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_lead_id'), 'enrollments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_enrollments_next_run_at'), 'enrollments', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_enrollments_sequence_id'), 'enrollments', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_table('events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('value_cents', sa.Integer(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('utm', sa.JSON(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_brand_id'), 'events', ['brand_id'], unique=False)
    op.create_index(op.f('ix_events_contact_id'), 'events', ['contact_id'], unique=False)
    op.create_index(op.f('ix_events_deleted_at'), 'events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_lead_id'), 'events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_table('form_submissions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('utm', sa.JSON(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_brand_id'), 'form_submissions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_deleted_at'), 'form_submissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_form_submissions_form_id'), 'form_submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_id'), 'form_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_form_submissions_lead_id'), 'form_submissions', ['lead_id'], unique=False)
    op.create_table('landing_pages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('form_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('subheadline', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('cta_label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('cta_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('seo_meta', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_pages_brand_id'), 'landing_pages', ['brand_id'], unique=False)
    op.create_index(op.f('ix_landing_pages_campaign_id'), 'landing_pages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_landing_pages_deleted_at'), 'landing_pages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_landing_pages_id'), 'landing_pages', ['id'], unique=False)
    op.create_index(op.f('ix_landing_pages_is_published'), 'landing_pages', ['is_published'], unique=False)
    op.create_index(op.f('ix_landing_pages_slug'), 'landing_pages', ['slug'], unique=True)
    op.create_table('lead_tags',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'tag_id', name='uq_lead_tag')
    )
    op.create_index(op.f('ix_lead_tags_deleted_at'), 'lead_tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_lead_tags_id'), 'lead_tags', ['id'], unique=False)
    op.create_index(op.f('ix_lead_tags_lead_id'), 'lead_tags', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_tags_tag_id'), 'lead_tags', ['tag_id'], unique=False)
    op.create_table('revenue_records',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('stripe_object_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_records_brand_id'), 'revenue_records', ['brand_id'], unique=False)
    op.create_index(op.f('ix_revenue_records_deleted_at'), 'revenue_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_revenue_records_id'), 'revenue_records', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_records_occurred_at'), 'revenue_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_revenue_records_offer_id'), 'revenue_records', ['offer_id'], unique=False)
    op.create_index(op.f('ix_revenue_records_status'), 'revenue_records', ['status'], unique=False)
    op.create_index(op.f('ix_revenue_records_stripe_object_id'), 'revenue_records', ['stripe_object_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('social_campaign_id', sa.Uuid(), nullable=True),
    sa.Column('social_account_id', sa.Uuid(), nullable=True),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('external_post_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['social_campaign_id'], ['social_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_brand_id'), 'social_posts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_social_posts_deleted_at'), 'social_posts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_social_posts_id'), 'social_posts', ['id'], unique=False)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_posts_scheduled_at'), 'social_posts', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_social_posts_social_campaign_id'), 'social_posts', ['social_campaign_id'], unique=False)
    op.create_index(op.f('ix_social_posts_state'), 'social_posts', ['state'], unique=False)
    op.create_table('step_runs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_step_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_message_id', sa.Uuid(), nullable=True),
    sa.Column('variant_label', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['sequence_step_id'], ['sequence_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_runs_deleted_at'), 'step_runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_step_runs_email_message_id'), 'step_runs', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_step_runs_enrollment_id'), 'step_runs', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_step_runs_id'), 'step_runs', ['id'], unique=False)
    op.create_index(op.f('ix_step_runs_scheduled_at'), 'step_runs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_step_runs_sequence_step_id'), 'step_runs', ['sequence_step_id'], unique=False)
    op.create_index(op.f('ix_step_runs_status'), 'step_runs', ['status'], unique=False)
    op.create_table('utm_captures',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('form_submission_id', sa.Uuid(), nullable=True),
    sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_medium', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_term', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('utm_content', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('landing_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['form_submission_id'], ['form_submissions.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utm_captures_brand_id'), 'utm_captures', ['brand_id'], unique=False)
    op.create_index(op.f('ix_utm_captures_deleted_at'), 'utm_captures', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_utm_captures_id'), 'utm_captures', ['id'], unique=False)
    op.create_index(op.f('ix_utm_captures_lead_id'), 'utm_captures', ['lead_id'], unique=False)
    op.create_index(op.f('ix_utm_captures_utm_campaign'), 'utm_captures', ['utm_campaign'], unique=False)
    op.create_index(op.f('ix_utm_captures_utm_source'), 'utm_captures', ['utm_source'], unique=False)
    op.create_table('email_messages',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('step_run_id', sa.Uuid(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('to_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('from_email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('from_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('variant_label', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['step_run_id'], ['step_runs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_brand_id'), 'email_messages', ['brand_id'], unique=False)
    op.create_index(op.f('ix_email_messages_campaign_id'), 'email_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_email_messages_contact_id'), 'email_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_email_messages_deleted_at'), 'email_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.create_index(op.f('ix_email_messages_lead_id'), 'email_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_messages_provider_message_id'), 'email_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_scheduled_at'), 'email_messages', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_email_messages_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('ix_email_messages_step_run_id'), 'email_messages', ['step_run_id'], unique=False)
    op.create_index(op.f('ix_email_messages_to_email'), 'email_messages', ['to_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_to_email'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_step_run_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_status'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_scheduled_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_lead_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_deleted_at'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_contact_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_campaign_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_brand_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_utm_captures_utm_source'), table_name='utm_captures')
    op.drop_index(op.f('ix_utm_captures_utm_campaign'), table_name='utm_captures')
    op.drop_index(op.f('ix_utm_captures_lead_id'), table_name='utm_captures')
    op.drop_index(op.f('ix_utm_captures_id'), table_name='utm_captures')
    op.drop_index(op.f('ix_utm_captures_deleted_at'), table_name='utm_captures')
    op.drop_index(op.f('ix_utm_captures_brand_id'), table_name='utm_captures')
    op.drop_table('utm_captures')
    op.drop_index(op.f('ix_step_runs_status'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_sequence_step_id'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_scheduled_at'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_id'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_enrollment_id'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_email_message_id'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_deleted_at'), table_name='step_runs')
    op.drop_table('step_runs')
    op.drop_index(op.f('ix_social_posts_state'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_social_campaign_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_scheduled_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_deleted_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_brand_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_revenue_records_stripe_object_id'), table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_status'), table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_offer_id'), table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_occurred_at'), table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_id'), table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_deleted_at'), table_name='revenue_records')
    op.drop_index(op.f('ix_revenue_records_brand_id'), table_name='revenue_records')
    op.drop_table('revenue_records')
    op.drop_index(op.f('ix_lead_tags_tag_id'), table_name='lead_tags')
    op.drop_index(op.f('ix_lead_tags_lead_id'), table_name='lead_tags')
    op.drop_index(op.f('ix_lead_tags_id'), table_name='lead_tags')
    op.drop_index(op.f('ix_lead_tags_deleted_at'), table_name='lead_tags')
    op.drop_table('lead_tags')
    op.drop_index(op.f('ix_landing_pages_slug'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_is_published'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_deleted_at'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_campaign_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_brand_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_form_submissions_lead_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_deleted_at'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_brand_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_lead_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_deleted_at'), table_name='events')
    op.drop_index(op.f('ix_events_contact_id'), table_name='events')
    op.drop_index(op.f('ix_events_brand_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_sequence_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_next_run_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_lead_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_deleted_at'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_contact_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_brand_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_content_items_state'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_social_campaign_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_scheduled_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_deleted_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_channel'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_campaign_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_brand_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_consent_records_lead_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_deleted_at'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_brand_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_ab_tests_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_deleted_at'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_brand_id'), table_name='ab_tests')
    op.drop_table('ab_tests')
    op.drop_index(op.f('ix_social_campaigns_status'), table_name='social_campaigns')
    op.drop_index(op.f('ix_social_campaigns_id'), table_name='social_campaigns')
    op.drop_index(op.f('ix_social_campaigns_deleted_at'), table_name='social_campaigns')
    op.drop_index(op.f('ix_social_campaigns_brand_id'), table_name='social_campaigns')
    op.drop_table('social_campaigns')
    op.drop_index(op.f('ix_sequence_steps_sequence_id'), table_name='sequence_steps')
    op.drop_index(op.f('ix_sequence_steps_id'), table_name='sequence_steps')
    op.drop_index(op.f('ix_sequence_steps_deleted_at'), table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_double_optin_token'), table_name='leads')
    op.drop_index(op.f('ix_leads_deleted_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_consent_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_brand_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_index(op.f('ix_forms_id'), table_name='forms')
    op.drop_index(op.f('ix_forms_deleted_at'), table_name='forms')
    op.drop_index(op.f('ix_forms_brand_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_pipeline_stage_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_owner_user_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_deleted_at'), table_name='deals')
    op.drop_index(op.f('ix_deals_contact_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_brand_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_sequences_status'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_slug'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_id'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_deleted_at'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_brand_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_revenue_goals_id'), table_name='revenue_goals')
    op.drop_index(op.f('ix_revenue_goals_deleted_at'), table_name='revenue_goals')
    op.drop_index(op.f('ix_revenue_goals_brand_id'), table_name='revenue_goals')
    op.drop_table('revenue_goals')
    op.drop_index(op.f('ix_ctas_id'), table_name='ctas')
    op.drop_index(op.f('ix_ctas_deleted_at'), table_name='ctas')
    op.drop_index(op.f('ix_ctas_brand_id'), table_name='ctas')
    op.drop_table('ctas')
    op.drop_index(op.f('ix_contacts_source'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_owner_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lifecycle_stage'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lead_score'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_deleted_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_brand_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_slug'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_deleted_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_utm_links_short_code'), table_name='utm_links')
    op.drop_index(op.f('ix_utm_links_id'), table_name='utm_links')
    op.drop_index(op.f('ix_utm_links_deleted_at'), table_name='utm_links')
    op.drop_index(op.f('ix_utm_links_brand_id'), table_name='utm_links')
    op.drop_table('utm_links')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_reminder_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_brand_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.drop_index(op.f('ix_tags_brand_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_suppressions_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_email'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_deleted_at'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_brand_id'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_deleted_at'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_brand_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_sender_identities_id'), table_name='sender_identities')
    op.drop_index(op.f('ix_sender_identities_deleted_at'), table_name='sender_identities')
    op.drop_index(op.f('ix_sender_identities_brand_id'), table_name='sender_identities')
    op.drop_table('sender_identities')
    op.drop_index(op.f('ix_segments_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_deleted_at'), table_name='segments')
    op.drop_index(op.f('ix_segments_brand_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_pipeline_stages_slug'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_id'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_deleted_at'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_brand_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_pillars_id'), table_name='pillars')
    op.drop_index(op.f('ix_pillars_deleted_at'), table_name='pillars')
    op.drop_index(op.f('ix_pillars_brand_id'), table_name='pillars')
    op.drop_table('pillars')
    op.drop_index(op.f('ix_offers_slug'), table_name='offers')
    op.drop_index(op.f('ix_offers_name'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_deleted_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_brand_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_entity_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_deleted_at'), table_name='notes')
    op.drop_index(op.f('ix_notes_brand_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_hooks_id'), table_name='hooks')
    op.drop_index(op.f('ix_hooks_deleted_at'), table_name='hooks')
    op.drop_index(op.f('ix_hooks_brand_id'), table_name='hooks')
    op.drop_table('hooks')
    op.drop_index(op.f('ix_hashtags_tag'), table_name='hashtags')
    op.drop_index(op.f('ix_hashtags_id'), table_name='hashtags')
    op.drop_index(op.f('ix_hashtags_deleted_at'), table_name='hashtags')
    op.drop_index(op.f('ix_hashtags_brand_id'), table_name='hashtags')
    op.drop_table('hashtags')
    op.drop_index(op.f('ix_email_templates_slug'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_deleted_at'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_brand_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_conversion_goals_id'), table_name='conversion_goals')
    op.drop_index(op.f('ix_conversion_goals_deleted_at'), table_name='conversion_goals')
    op.drop_index(op.f('ix_conversion_goals_brand_id'), table_name='conversion_goals')
    op.drop_table('conversion_goals')
    op.drop_index(op.f('ix_content_calendars_id'), table_name='content_calendars')
    op.drop_index(op.f('ix_content_calendars_deleted_at'), table_name='content_calendars')
    op.drop_index(op.f('ix_content_calendars_brand_id'), table_name='content_calendars')
    op.drop_table('content_calendars')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_deleted_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_brand_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_buyer_personas_id'), table_name='buyer_personas')
    op.drop_index(op.f('ix_buyer_personas_deleted_at'), table_name='buyer_personas')
    op.drop_index(op.f('ix_buyer_personas_brand_id'), table_name='buyer_personas')
    op.drop_table('buyer_personas')
    op.drop_index(op.f('ix_brand_voices_id'), table_name='brand_voices')
    op.drop_index(op.f('ix_brand_voices_deleted_at'), table_name='brand_voices')
    op.drop_index(op.f('ix_brand_voices_brand_id'), table_name='brand_voices')
    op.drop_table('brand_voices')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deleted_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_audiences_id'), table_name='audiences')
    op.drop_index(op.f('ix_audiences_deleted_at'), table_name='audiences')
    op.drop_index(op.f('ix_audiences_brand_id'), table_name='audiences')
    op.drop_table('audiences')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requested_by_user_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_deleted_at'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_brand_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_action_type'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_deleted_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_deleted_at'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_deleted_at'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
