"""media pipeline

Revision ID: b0d35cc5876e
Revises: 2d537fa5afd6
Create Date: 2026-06-29 21:51:52.637912+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0d35cc5876e'
down_revision: str | None = '2d537fa5afd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('uploader_user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('original_path', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_brand_id'), 'media_assets', ['brand_id'], unique=False)
    op.create_index(op.f('ix_media_assets_checksum'), 'media_assets', ['checksum'], unique=False)
    op.create_index(op.f('ix_media_assets_deleted_at'), 'media_assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_index(op.f('ix_media_assets_kind'), 'media_assets', ['kind'], unique=False)
    op.create_index(op.f('ix_media_assets_status'), 'media_assets', ['status'], unique=False)
    op.create_table('media_variants',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('aspect_ratio', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_ai_enhanced', sa.Boolean(), nullable=False),
    sa.Column('enhancement', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_variants_deleted_at'), 'media_variants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_variants_id'), 'media_variants', ['id'], unique=False)
    op.create_index(op.f('ix_media_variants_media_asset_id'), 'media_variants', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_media_variants_platform'), 'media_variants', ['platform'], unique=False)
    op.create_index(op.f('ix_media_variants_state'), 'media_variants', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_variants_state'), table_name='media_variants')
    op.drop_index(op.f('ix_media_variants_platform'), table_name='media_variants')
    op.drop_index(op.f('ix_media_variants_media_asset_id'), table_name='media_variants')
    op.drop_index(op.f('ix_media_variants_id'), table_name='media_variants')
    op.drop_index(op.f('ix_media_variants_deleted_at'), table_name='media_variants')
    op.drop_table('media_variants')
    op.drop_index(op.f('ix_media_assets_status'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_kind'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_deleted_at'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_checksum'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_brand_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
